import { useEffect, useRef } from 'react'
import * as THREE from 'three'

const material = (color:number, emissive=0) => new THREE.MeshStandardMaterial({ color, emissive, emissiveIntensity: emissive ? .42 : 0, roughness:.8, flatShading:true })

export const RubyBattleMap = ({ onBack }: { onBack: () => void }) => {
  const mountRef = useRef<HTMLDivElement>(null)
  useEffect(() => {
    const host=mountRef.current;if(!host)return
    const scene=new THREE.Scene();scene.background=new THREE.Color(0x4b2033);scene.fog=new THREE.Fog(0x4b2033,30,74)
    const camera=new THREE.OrthographicCamera(-24,24,13.5,-13.5,.1,120);camera.position.set(24,29,27);camera.lookAt(0,0,0)
    const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement)
    scene.add(new THREE.HemisphereLight(0xffd1ca,0x351526,2.2));const sun=new THREE.DirectionalLight(0xffb4a8,2.45);sun.position.set(-18,29,15);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-28;sun.shadow.camera.right=28;sun.shadow.camera.top=28;sun.shadow.camera.bottom=-28;scene.add(sun)
    const world=new THREE.Group();scene.add(world)
    const ground=new THREE.Mesh(new THREE.PlaneGeometry(130,100),material(0x562332));ground.rotation.x=-Math.PI/2;ground.position.y=-.05;ground.receiveShadow=true;world.add(ground)
    const plateau=new THREE.Mesh(new THREE.CircleGeometry(27,48),material(0x903546));plateau.rotation.x=-Math.PI/2;plateau.scale.z=.76;plateau.position.y=.01;plateau.receiveShadow=true;world.add(plateau)
    const pathMat=material(0x4a2634)
    // The roads use irregular ribbon shapes, matching the lived-in paths of the home kingdom.
    const addPath=(x1:number,z1:number,x2:number,z2:number,width=1.15)=>{const dx=x2-x1,dz=z2-z1,distance=Math.hypot(dx,dz),bend=(.45+Math.abs(Math.sin(x1*4+z2))* .5)*Math.min(2.3,distance*.15);const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(x1,.06,z1),new THREE.Vector3(x1+dx*.3-dz/distance*bend,.06,z1+dz*.3+dx/distance*bend),new THREE.Vector3(x1+dx*.7+dz/distance*bend*.6,.06,z1+dz*.7-dx/distance*bend*.6),new THREE.Vector3(x2,.06,z2)]);const left:THREE.Vector2[]=[],right:THREE.Vector2[]=[];for(let i=0;i<=28;i++){const point=curve.getPoint(i/28),tangent=curve.getTangent(i/28).normalize(),edge=width*.5*(.86+Math.sin(i*2.3)*.11);left.push(new THREE.Vector2(point.x-tangent.z*edge,-point.z-tangent.x*edge));right.push(new THREE.Vector2(point.x+tangent.z*edge,-point.z+tangent.x*edge))}const shape=new THREE.Shape();shape.moveTo(left[0].x,left[0].y);left.slice(1).forEach(p=>shape.lineTo(p.x,p.y));right.reverse().forEach(p=>shape.lineTo(p.x,p.y));shape.closePath();const mesh=new THREE.Mesh(new THREE.ShapeGeometry(shape));mesh.geometry.rotateX(-Math.PI/2);mesh.material=pathMat;mesh.position.y=.075;mesh.receiveShadow=true;world.add(mesh)}
    addPath(0,-4.8,0,-15,1.5);addPath(4.7,0,13,0,1.35);addPath(-4.7,0,-13,1,1.35);addPath(0,4.6,0,17,1.45);addPath(-13,1,-13,8,.9);addPath(13,0,14,-8,.9);addPath(0,-15,-10,-12,.9);addPath(0,17,10,13,.85)
    const roadHub=new THREE.Mesh(new THREE.CircleGeometry(5.5,30),pathMat);roadHub.rotation.x=-Math.PI/2;roadHub.position.y=.06;world.add(roadHub)
    const crystalPulse:THREE.Mesh[]=[]
    const crystal=(x:number,z:number,scale=1,color=0xef334c)=>{const group=new THREE.Group();group.position.set(x,.18,z);group.scale.setScalar(scale);world.add(group);for(let i=0;i<3;i++){const a=i*2.1;const gem=new THREE.Mesh(new THREE.OctahedronGeometry(.5+i*.12,0),material(color,color));gem.position.set(Math.cos(a)*(.5+i*.11),.55+i*.16,Math.sin(a)*(.5+i*.11));gem.scale.y=1.9;gem.rotation.y=a*.7;gem.castShadow=true;group.add(gem);crystalPulse.push(gem)}const base=new THREE.Mesh(new THREE.CylinderGeometry(.8,1.05,.3,7),material(0x562b38));base.position.y=.15;group.add(base)}
    ;[[-17,-8,1.2],[-18,8,1.05],[-11,14,.85],[15,-9,1.15],[18,6,.9],[7,16,.75],[-5,-15,.9],[14,13,.85],[-20,-1,.8]].forEach(([x,z,s])=>crystal(x,z,s))
    const addPalaceTower=(x:number,z:number,height:number)=>{const tower=new THREE.Mesh(new THREE.CylinderGeometry(1.08,1.2,height,8),material(0xa6424e));tower.position.set(x,height/2+.35,z);tower.castShadow=true;world.add(tower);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.35,1.75,6),material(0x6f1d38));roof.position.set(x,height+1.2,z);roof.castShadow=true;world.add(roof);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.13,.1,5,8),material(0xf2bd63));ring.rotation.x=Math.PI/2;ring.position.set(x,height+.2,z);world.add(ring)}
    const palaceBase=new THREE.Mesh(new THREE.CylinderGeometry(4.7,5.05,1.05,9),material(0x582f3b));palaceBase.position.y=.53;palaceBase.castShadow=true;world.add(palaceBase)
    const keep=new THREE.Mesh(new THREE.BoxGeometry(4.4,4.6,3.9),material(0xb14854));keep.position.set(0,2.65,.3);keep.castShadow=true;world.add(keep)
    const gate=new THREE.Mesh(new THREE.BoxGeometry(1.1,1.75,.08),material(0x401e2d));gate.position.set(0,1.25,2.3);world.add(gate)
    ;[-1.25,0,1.25].forEach((x)=>{const window=new THREE.Mesh(new THREE.CircleGeometry(.21,7),material(0xffcf6d,0xffcf6d));window.position.set(x,3.2,2.27);world.add(window)})
    addPalaceTower(-3.1,-2.85,4.3);addPalaceTower(3.1,-2.85,4.3);addPalaceTower(-3.1,2.85,4);addPalaceTower(3.1,2.85,4)
    const royalRuby=new THREE.Mesh(new THREE.OctahedronGeometry(1.05,0),material(0xff3657,0xff3657));royalRuby.position.set(0,6.25,.3);royalRuby.scale.y=1.6;royalRuby.castShadow=true;world.add(royalRuby);crystalPulse.push(royalRuby)
    const addOutpost=(x:number,z:number,roof:number)=>{const base=new THREE.Mesh(new THREE.CylinderGeometry(1.23,1.4,1.5,7),material(0x9b404c));base.position.set(x,1.1,z);base.castShadow=true;world.add(base);const roofMesh=new THREE.Mesh(new THREE.ConeGeometry(1.65,1.5,6),material(roof));roofMesh.position.set(x,2.65,z);roofMesh.castShadow=true;world.add(roofMesh);const banner=new THREE.Mesh(new THREE.PlaneGeometry(.62,.95),new THREE.MeshBasicMaterial({color:0xf4bb59,side:THREE.DoubleSide}));banner.position.set(x+.1,4.15,z);world.add(banner)}
    ;[[-12,6,0x6a203a],[11,-6,0x74223d],[-9,-12,0x80283f],[13,10,0x67203a]].forEach(([x,z,roof])=>addOutpost(x,z,roof))
    // Occupied ruby villages: rounded homes, proper roofs, doors, windows, and small civic spaces.
    const addRubyHome=(x:number,z:number,roofColor=0x6c203d,scale=.9)=>{const home=new THREE.Group();home.position.set(x,.35,z);home.scale.setScalar(scale);world.add(home);const footing=new THREE.Mesh(new THREE.CylinderGeometry(1.35,1.5,.28,8),material(0x63303d));footing.position.y=.14;home.add(footing);const walls=new THREE.Mesh(new THREE.CylinderGeometry(1.16,1.28,1.68,8),material(0xb84c57));walls.position.y=1;walls.castShadow=true;home.add(walls);const eave=new THREE.Mesh(new THREE.TorusGeometry(1.23,.1,6,8),material(0xf1bd64));eave.rotation.x=Math.PI/2;eave.position.y=1.79;home.add(eave);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.62,1.72,7),material(roofColor));roof.position.y=2.75;roof.rotation.y=.3;roof.castShadow=true;home.add(roof);const door=new THREE.Mesh(new THREE.PlaneGeometry(.48,.86),material(0x491e2d));door.position.set(0,.75,1.3);door.rotation.y=Math.PI;home.add(door);[-.48,.48].forEach(side=>{const window=new THREE.Mesh(new THREE.CircleGeometry(.15,7),material(0xffd46e,0xffb336));window.position.set(side,1.18,1.18);window.rotation.y=Math.PI;home.add(window)});const chimney=new THREE.Mesh(new THREE.CylinderGeometry(.14,.18,.7,6),material(0x6b3540));chimney.position.set(.52,3.1,.1);home.add(chimney)}
    ;[[-16,5,.88],[-14,8,.78],[-17,10,.73],[-15,-6,.86],[-17,-10,.75],[15,-4,.9],[17,-2,.76],[18,-8,.76],[-5,-14,.82],[-1,-16,.88],[5,-15,.76],[14,12,.82],[9,16,.76]].forEach(([x,z,s],i)=>addRubyHome(x,z,i%2?0x7a2542:0x5a2440,s))
    const addRubyWell=(x:number,z:number)=>{const well=new THREE.Group();well.position.set(x,.35,z);world.add(well);const base=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.2,.36,10),material(0x713744));base.position.y=.18;well.add(base);const wall=new THREE.Mesh(new THREE.CylinderGeometry(.82,.98,.6,10),material(0xad6261));wall.position.y=.56;well.add(wall);const rubyWater=new THREE.Mesh(new THREE.CircleGeometry(.68,12),material(0xff4762,0xff4762));rubyWater.rotation.x=-Math.PI/2;rubyWater.position.y=.9;well.add(rubyWater);[-.74,.74].forEach(px=>{const post=new THREE.Mesh(new THREE.CylinderGeometry(.08,.1,2,6),material(0x58303a));post.position.set(px,1.6,0);well.add(post)});const roof=new THREE.Mesh(new THREE.ConeGeometry(1.28,.92,4),material(0x69233d));roof.position.y=2.67;roof.rotation.y=Math.PI/4;well.add(roof)}
    addRubyWell(2.5,-12.2)
    const addRubyTree=(x:number,z:number,scale=.9)=>{const tree=new THREE.Group();tree.position.set(x,.3,z);tree.scale.setScalar(scale);world.add(tree);const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.13,.22,1.35,6),material(0x401f31));trunk.position.y=.68;tree.add(trunk);for(let i=0;i<3;i++){const crown=new THREE.Mesh(new THREE.OctahedronGeometry(.68-i*.08,0),material(i===1?0xa52e4d:0x772844));crown.position.set((i-1)*.27,1.65+i*.32,(i%2-.5)*.2);crown.scale.y=1.55;crown.castShadow=true;tree.add(crown)}}
    // Dense thorn-crystal woods extend well past the camera frame, with one deliberate palace exit opening.
    for(let band=0;band<8;band++)for(let i=0;i<58;i++){const angle=i/58*Math.PI*2+band*.18,radius=20+band*3+Math.sin(i*3.1+band)*.8,x=Math.cos(angle)*radius*1.18,z=Math.sin(angle)*radius*.82;if(z>7&&Math.abs(x)<3.8)continue;addRubyTree(x,z,.72+((i+band*2)%7)*.09)}
    for(let i=0;i<95;i++){const angle=i*2.16,r=7+(i%9)*1.55;const shard=new THREE.Mesh(new THREE.ConeGeometry(.035+(i%3)*.018,.22+(i%4)*.08,4),material(i%5?0xa83e50:0xff5b6f));shard.position.set(Math.cos(angle)*r,.14,Math.sin(angle)*r*.74);shard.rotation.z=(i%4-1.5)*.25;world.add(shard)}
    for(let i=0;i<45;i++){const a=i*2.4,r=17+(i%5)*2.4;const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.25+(i%4)*.09,0),material(i%4?0x6c2e3d:0xd84b59));rock.position.set(Math.cos(a)*r,.2,Math.sin(a)*r*.72);rock.rotation.y=i;world.add(rock)}
    const resize=()=>{const {width,height}=host.getBoundingClientRect(),half=13.5,aspect=width/height;camera.left=-half*aspect;camera.right=half*aspect;camera.top=half;camera.bottom=-half;renderer.setSize(width,height,false);camera.updateProjectionMatrix()};resize();window.addEventListener('resize',resize)
    let pointerX=0,pointerY=0,yaw=Math.atan2(27,24),height=29,frame=0
    const move=(event:PointerEvent)=>{const rect=host.getBoundingClientRect();pointerX=(event.clientX-rect.left)/rect.width-.5;pointerY=(event.clientY-rect.top)/rect.height-.5};host.addEventListener('pointermove',move)
    const animate=()=>{frame=requestAnimationFrame(animate);const time=performance.now()*.001;yaw+=((Math.atan2(27,24)+pointerX*.55)-yaw)*.05;height+=((29-pointerY*6)-height)*.05;camera.position.set(Math.cos(yaw)*35,height,Math.sin(yaw)*35);camera.lookAt(0,.8,0);world.rotation.y=Math.sin(time*.16)*.007;crystalPulse.forEach((gem,index)=>{const pulse=1+Math.sin(time*2.5+index)*.08;gem.scale.set(pulse,gem===royalRuby?1.6*pulse:1.9*pulse,pulse)});renderer.render(scene,camera)};animate()
    return()=>{cancelAnimationFrame(frame);window.removeEventListener('resize',resize);host.removeEventListener('pointermove',move);renderer.dispose();host.removeChild(renderer.domElement)}
  },[])
  return <section className="ruby-battle-map" aria-label="Empress Ruby battle map"><div ref={mountRef} className="ruby-battle-canvas" /><header><span>EMPERESS RUBY'S DOMAIN</span><b>CRIMSON JEWEL KINGDOM</b></header><button onClick={onBack}>‹ <span>RETREAT</span></button></section>
}
