import { useEffect, useRef, useState } from 'react'
import * as THREE from 'three'

const material = (color:number, emissive=0) => new THREE.MeshStandardMaterial({ color, emissive, emissiveIntensity: emissive ? .42 : 0, roughness:.8, flatShading:true })

export const RubyBattleMap = ({ onBack }: { onBack: () => void }) => {
  const mountRef = useRef<HTMLDivElement>(null)
  const [chatOpen, setChatOpen] = useState(true)
  useEffect(() => {
    const host=mountRef.current;if(!host)return
    const scene=new THREE.Scene();scene.background=new THREE.Color(0x4b2033);scene.fog=new THREE.Fog(0x4b2033,30,74)
    const camera=new THREE.OrthographicCamera(-24,24,13.5,-13.5,.1,120);camera.position.set(24,29,27);camera.lookAt(0,0,0)
    const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement)
    scene.add(new THREE.HemisphereLight(0xffd1ca,0x351526,2.2));const sun=new THREE.DirectionalLight(0xffb4a8,2.45);sun.position.set(-18,29,15);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-28;sun.shadow.camera.right=28;sun.shadow.camera.top=28;sun.shadow.camera.bottom=-28;scene.add(sun)
    const world=new THREE.Group();scene.add(world)
    const ground=new THREE.Mesh(new THREE.PlaneGeometry(130,100),material(0x562332));ground.rotation.x=-Math.PI/2;ground.position.y=-.05;ground.receiveShadow=true;world.add(ground)
    const plateau=new THREE.Mesh(new THREE.CircleGeometry(27,48),material(0x903546));plateau.rotation.x=-Math.PI/2;plateau.scale.z=.76;plateau.position.y=.01;plateau.receiveShadow=true;world.add(plateau)
    const pathMat=material(0x4a2634)
    // The roads use irregular ribbon shapes, matching the lived-in paths of the home kingdom.
    const addPath=(x1:number,z1:number,x2:number,z2:number,width=1.15)=>{const dx=x2-x1,dz=z2-z1,distance=Math.hypot(dx,dz),bend=(.45+Math.abs(Math.sin(x1*4+z2))* .5)*Math.min(2.3,distance*.15);const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(x1,.06,z1),new THREE.Vector3(x1+dx*.3-dz/distance*bend,.06,z1+dz*.3+dx/distance*bend),new THREE.Vector3(x1+dx*.7+dz/distance*bend*.6,.06,z1+dz*.7-dx/distance*bend*.6),new THREE.Vector3(x2,.06,z2)]);const left:THREE.Vector2[]=[],right:THREE.Vector2[]=[];for(let i=0;i<=28;i++){const point=curve.getPoint(i/28),tangent=curve.getTangent(i/28).normalize(),edge=width*.5*(.86+Math.sin(i*2.3)*.11);left.push(new THREE.Vector2(point.x-tangent.z*edge,-point.z-tangent.x*edge));right.push(new THREE.Vector2(point.x+tangent.z*edge,-point.z+tangent.x*edge))}const shape=new THREE.Shape();shape.moveTo(left[0].x,left[0].y);left.slice(1).forEach(p=>shape.lineTo(p.x,p.y));right.reverse().forEach(p=>shape.lineTo(p.x,p.y));shape.closePath();const mesh=new THREE.Mesh(new THREE.ShapeGeometry(shape));mesh.geometry.rotateX(-Math.PI/2);mesh.material=pathMat;mesh.position.y=.075;mesh.receiveShadow=true;world.add(mesh)}
    addPath(0,-4.8,0,-15,1.5);addPath(4.7,0,13,0,1.35);addPath(-4.7,0,-13,1,1.35);addPath(0,4.6,0,17,1.45);addPath(-13,1,-13,8,.9);addPath(13,0,14,-8,.9);addPath(0,-15,-10,-12,.9);addPath(0,17,10,13,.85);addPath(-13,8,-18,12,.82);addPath(13,0,18,7,.82);addPath(-13,1,-17,-9,.8);addPath(14,-8,17,-14,.8);addPath(0,17,-7,17,.75);addPath(0,-15,8,-16,.75)
    const roadHub=new THREE.Mesh(new THREE.CircleGeometry(5.5,30),pathMat);roadHub.rotation.x=-Math.PI/2;roadHub.position.y=.06;world.add(roadHub)
    const crystalPulse:THREE.Mesh[]=[]
    const crystal=(x:number,z:number,scale=1,color=0xef334c)=>{const group=new THREE.Group();group.position.set(x,.18,z);group.scale.setScalar(scale);world.add(group);for(let i=0;i<3;i++){const a=i*2.1;const gem=new THREE.Mesh(new THREE.OctahedronGeometry(.5+i*.12,0),material(color,color));gem.position.set(Math.cos(a)*(.5+i*.11),.55+i*.16,Math.sin(a)*(.5+i*.11));gem.scale.y=1.9;gem.rotation.y=a*.7;gem.castShadow=true;group.add(gem);crystalPulse.push(gem)}const base=new THREE.Mesh(new THREE.CylinderGeometry(.8,1.05,.3,7),material(0x562b38));base.position.y=.15;group.add(base)}
    ;[[-17,-8,1.2],[-18,8,1.05],[-11,14,.85],[15,-9,1.15],[18,6,.9],[7,16,.75],[-5,-15,.9],[14,13,.85],[-20,-1,.8]].forEach(([x,z,s])=>crystal(x,z,s))
    const addPalaceTower=(x:number,z:number,height:number)=>{const tower=new THREE.Mesh(new THREE.CylinderGeometry(1.08,1.2,height,8),material(0xa6424e));tower.position.set(x,height/2+.35,z);tower.castShadow=true;world.add(tower);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.35,1.75,6),material(0x6f1d38));roof.position.set(x,height+1.2,z);roof.castShadow=true;world.add(roof);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.13,.1,5,8),material(0xf2bd63));ring.rotation.x=Math.PI/2;ring.position.set(x,height+.2,z);world.add(ring)}
    const palaceBase=new THREE.Mesh(new THREE.CylinderGeometry(4.7,5.05,1.05,9),material(0x582f3b));palaceBase.position.y=.53;palaceBase.castShadow=true;world.add(palaceBase)
    const keep=new THREE.Mesh(new THREE.BoxGeometry(4.4,4.6,3.9),material(0xb14854));keep.position.set(0,2.65,.3);keep.castShadow=true;world.add(keep)
    const gate=new THREE.Mesh(new THREE.BoxGeometry(1.1,1.75,.08),material(0x401e2d));gate.position.set(0,1.25,2.3);world.add(gate)
    ;[-1.25,0,1.25].forEach((x)=>{const window=new THREE.Mesh(new THREE.CircleGeometry(.21,7),material(0xffcf6d,0xffcf6d));window.position.set(x,3.2,2.27);world.add(window)})
    addPalaceTower(-3.1,-2.85,4.3);addPalaceTower(3.1,-2.85,4.3);addPalaceTower(-3.1,2.85,4);addPalaceTower(3.1,2.85,4)
    const royalRuby=new THREE.Mesh(new THREE.OctahedronGeometry(1.05,0),material(0xff3657,0xff3657));royalRuby.position.set(0,6.25,.3);royalRuby.scale.y=1.6;royalRuby.castShadow=true;world.add(royalRuby);crystalPulse.push(royalRuby)
    const addOutpost=(x:number,z:number,roof:number)=>{const base=new THREE.Mesh(new THREE.CylinderGeometry(1.23,1.4,1.5,7),material(0x9b404c));base.position.set(x,1.1,z);base.castShadow=true;world.add(base);const roofMesh=new THREE.Mesh(new THREE.ConeGeometry(1.65,1.5,6),material(roof));roofMesh.position.set(x,2.65,z);roofMesh.castShadow=true;world.add(roofMesh);const banner=new THREE.Mesh(new THREE.PlaneGeometry(.62,.95),new THREE.MeshBasicMaterial({color:0xf4bb59,side:THREE.DoubleSide}));banner.position.set(x+.1,4.15,z);world.add(banner)}
    ;[[-12,6,0x6a203a],[11,-6,0x74223d],[-9,-12,0x80283f],[13,10,0x67203a]].forEach(([x,z,roof])=>addOutpost(x,z,roof))
    // Occupied ruby villages: rounded homes, proper roofs, doors, windows, and small civic spaces.
    const addRubyHome=(x:number,z:number,roofColor=0x6c203d,scale=.9)=>{const home=new THREE.Group();home.position.set(x,.35,z);home.scale.setScalar(scale);world.add(home);const footing=new THREE.Mesh(new THREE.CylinderGeometry(1.35,1.5,.28,8),material(0x63303d));footing.position.y=.14;home.add(footing);const walls=new THREE.Mesh(new THREE.CylinderGeometry(1.16,1.28,1.68,8),material(0xb84c57));walls.position.y=1;walls.castShadow=true;home.add(walls);const eave=new THREE.Mesh(new THREE.TorusGeometry(1.23,.1,6,8),material(0xf1bd64));eave.rotation.x=Math.PI/2;eave.position.y=1.79;home.add(eave);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.62,1.72,7),material(roofColor));roof.position.y=2.75;roof.rotation.y=.3;roof.castShadow=true;home.add(roof);const door=new THREE.Mesh(new THREE.PlaneGeometry(.48,.86),material(0x491e2d));door.position.set(0,.75,1.3);door.rotation.y=Math.PI;home.add(door);[-.48,.48].forEach(side=>{const window=new THREE.Mesh(new THREE.CircleGeometry(.15,7),material(0xffd46e,0xffb336));window.position.set(side,1.18,1.18);window.rotation.y=Math.PI;home.add(window)});const chimney=new THREE.Mesh(new THREE.CylinderGeometry(.14,.18,.7,6),material(0x6b3540));chimney.position.set(.52,3.1,.1);home.add(chimney)}
    ;[[-16,5,.88],[-14,8,.78],[-17,10,.73],[-15,-6,.86],[-17,-10,.75],[15,-4,.9],[17,-2,.76],[18,-8,.76],[-5,-14,.82],[-1,-16,.88],[5,-15,.76],[14,12,.82],[9,16,.76]].forEach(([x,z,s],i)=>addRubyHome(x,z,i%2?0x7a2542:0x5a2440,s))
    const addRubyWell=(x:number,z:number)=>{const well=new THREE.Group();well.position.set(x,.35,z);world.add(well);const base=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.2,.36,10),material(0x713744));base.position.y=.18;well.add(base);const wall=new THREE.Mesh(new THREE.CylinderGeometry(.82,.98,.6,10),material(0xad6261));wall.position.y=.56;well.add(wall);const rubyWater=new THREE.Mesh(new THREE.CircleGeometry(.68,12),material(0xff4762,0xff4762));rubyWater.rotation.x=-Math.PI/2;rubyWater.position.y=.9;well.add(rubyWater);[-.74,.74].forEach(px=>{const post=new THREE.Mesh(new THREE.CylinderGeometry(.08,.1,2,6),material(0x58303a));post.position.set(px,1.6,0);well.add(post)});const roof=new THREE.Mesh(new THREE.ConeGeometry(1.28,.92,4),material(0x69233d));roof.position.y=2.67;roof.rotation.y=Math.PI/4;well.add(roof)}
    addRubyWell(2.5,-12.2)
    const addLantern=(x:number,z:number)=>{const post=new THREE.Group();post.position.set(x,.34,z);world.add(post);const pole=new THREE.Mesh(new THREE.CylinderGeometry(.045,.06,1.45,6),material(0x4a2231));pole.position.y=.72;post.add(pole);const light=new THREE.Mesh(new THREE.OctahedronGeometry(.18),material(0xffc55b,0xffb339));light.position.y=1.5;post.add(light)}
    ;[[-2,6.6],[2,6.6],[-12,4],[-12,-7],[11,-5],[7,12],[-16,9],[15,-9]].forEach(([x,z])=>addLantern(x,z))
    const addStable=(x:number,z:number)=>{const stable=new THREE.Group();stable.position.set(x,.35,z);world.add(stable);const floor=new THREE.Mesh(new THREE.BoxGeometry(3.6,.18,2.8),material(0x6a3942));floor.position.y=.09;stable.add(floor);const back=new THREE.Mesh(new THREE.BoxGeometry(3.35,2.25,.16),material(0x984850));back.position.set(0,1.2,-1.25);stable.add(back);[[-1.45,-1.1],[1.45,-1.1],[-1.45,1.1],[1.45,1.1]].forEach(([px,pz])=>{const post=new THREE.Mesh(new THREE.CylinderGeometry(.1,.13,2.7,6),material(0x4c2932));post.position.set(px,1.35,pz);stable.add(post)});const roof=new THREE.Mesh(new THREE.ConeGeometry(2.55,1.45,4),material(0x67213b));roof.position.y=3.08;roof.rotation.y=Math.PI/4;stable.add(roof);[-.65,.65].forEach(px=>{const horse=new THREE.Mesh(new THREE.SphereGeometry(.46,7,6),material(0x733847));horse.scale.set(1.35,.75,.75);horse.position.set(px,.72,.12);stable.add(horse);const head=new THREE.Mesh(new THREE.SphereGeometry(.2,6,5),material(0x562b37));head.position.set(px+.55,1.05,.12);stable.add(head)})}
    const addWindmill=(x:number,z:number)=>{const mill=new THREE.Group();mill.position.set(x,.35,z);world.add(mill);const base=new THREE.Mesh(new THREE.CylinderGeometry(1.15,1.4,2.8,8),material(0xad5058));base.position.y=1.4;mill.add(base);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.45,1.5,6),material(0x64203b));roof.position.y=3.55;mill.add(roof);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.23,.23,.24,8),material(0xf1bd63));hub.position.set(0,2.75,1.18);hub.rotation.x=Math.PI/2;mill.add(hub);for(let i=0;i<4;i++){const blade=new THREE.Mesh(new THREE.BoxGeometry(.28,1.58,.09),material(i%2?0xe9b44f:0x72253e));blade.position.set(Math.sin(i*Math.PI/2)*.67,2.75+Math.cos(i*Math.PI/2)*.67,1.23);blade.rotation.z=-i*Math.PI/2;mill.add(blade)}}
    const addEmberFarm=(x:number,z:number)=>{const soil=new THREE.Mesh(new THREE.PlaneGeometry(5.2,3.7),material(0x6b2b36));soil.rotation.x=-Math.PI/2;soil.position.set(x,.07,z);world.add(soil);for(let row=0;row<4;row++)for(let col=0;col<6;col++){const crop=new THREE.Mesh(new THREE.ConeGeometry(.1,.58,5),material((row+col)%3?0xc54755:0xf2a449));crop.position.set(x-1.65+col*.66,.34,z-1.05+row*.68);world.add(crop)};[[0,-1.85,5.3,.12],[0,1.85,5.3,.12],[-2.65,0,.12,3.8],[2.65,0,.12,3.8]].forEach(([dx,dz,w,d])=>{const rail=new THREE.Mesh(new THREE.BoxGeometry(w,.14,d),material(0x4e2932));rail.position.set(x+dx,.46,z+dz);world.add(rail)});addRubyHome(x-3.8,z+1.2,0x5e243e,.88)}
    const addMarket=(x:number,z:number)=>{const market=new THREE.Group();market.position.set(x,.35,z);world.add(market);const table=new THREE.Mesh(new THREE.BoxGeometry(2.7,.7,1.2),material(0x69333c));table.position.y=.72;market.add(table);const canopy=new THREE.Mesh(new THREE.ConeGeometry(2.0,.65,4),material(0x6e203c));canopy.position.y=2.5;canopy.rotation.y=Math.PI/4;market.add(canopy);[[-1.1,-.45],[1.1,-.45],[-1.1,.45],[1.1,.45]].forEach(([px,pz])=>{const pole=new THREE.Mesh(new THREE.CylinderGeometry(.06,.08,2.05,5),material(0x4a2731));pole.position.set(px,1.3,pz);market.add(pole)});[-.65,0,.65].forEach((px,i)=>{const gem=new THREE.Mesh(new THREE.OctahedronGeometry(.22),material(i===1?0xf2be5a:0xe13f59));gem.position.set(px,1.2,0);market.add(gem)})}
    const addForge=(x:number,z:number)=>{const forge=new THREE.Group();forge.position.set(x,.35,z);world.add(forge);const body=new THREE.Mesh(new THREE.CylinderGeometry(1.22,1.4,1.75,8),material(0x743946));body.position.y=.95;forge.add(body);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.6,1.25,6),material(0x3f2631));roof.position.y=2.4;forge.add(roof);const chimney=new THREE.Mesh(new THREE.CylinderGeometry(.22,.27,1.45,7),material(0x502b34));chimney.position.set(.55,3.05,0);forge.add(chimney);const door=new THREE.Mesh(new THREE.CircleGeometry(.36,7),material(0xffa147,0xff7b35));door.position.set(0,.88,1.24);door.rotation.y=Math.PI;forge.add(door)}
    const addWatchPost=(x:number,z:number)=>{const post=new THREE.Group();post.position.set(x,.35,z);world.add(post);const base=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.28,.36,8),material(0x623540));base.position.y=.18;post.add(base);for(let i=0;i<4;i++){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.09,.12,2.55,6),material(0x4a2831));leg.position.set(Math.cos(i*Math.PI/2)*.7,1.55,Math.sin(i*Math.PI/2)*.7);post.add(leg)}const deck=new THREE.Mesh(new THREE.CylinderGeometry(1.08,1.08,.18,8),material(0xa94b55));deck.position.y=2.78;post.add(deck);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.35,1.1,6),material(0x62213a));roof.position.y=3.45;post.add(roof)}
    addStable(-7.5,12);addWindmill(13,-13);addEmberFarm(-13,-13);addMarket(12,7);addForge(-12,-3);addWatchPost(-19,12);addWatchPost(18,-13);addWatchPost(-6,18);addWatchPost(6,18)
    // A complete green home kingdom borders Ruby's realm to the west, rather than a token outpost.
    const addHomeRealm=(x:number,z:number)=>{const meadow=new THREE.Mesh(new THREE.CircleGeometry(20,42),material(0x91b989));meadow.rotation.x=-Math.PI/2;meadow.scale.z=.78;meadow.position.set(x,.035,z);world.add(meadow);const plaza=new THREE.Mesh(new THREE.CircleGeometry(4.7,30),material(0xd4d0bf));plaza.rotation.x=-Math.PI/2;plaza.position.set(x,.08,z);world.add(plaza);addPath(x,z-4.2,x,z-13,1.25);addPath(x+4,z,x+12,z,.95);addPath(x-4,z,x-12,z+1,.95);addPath(x,z+4,x+1,z+12,.95);const base=new THREE.Mesh(new THREE.CylinderGeometry(4.25,4.55,.9,8),material(0x777a74));base.position.set(x,.49,z);world.add(base);const keep=new THREE.Mesh(new THREE.BoxGeometry(4,4.3,3.55),material(0xc7bdaa));keep.position.set(x,2.55,z+.2);world.add(keep);const gate=new THREE.Mesh(new THREE.BoxGeometry(1.05,1.6,.08),material(0x694534));gate.position.set(x,1.16,z+2.05);world.add(gate);[-1.2,0,1.2].forEach(px=>{const win=new THREE.Mesh(new THREE.CircleGeometry(.19,7),material(0x557f9b));win.position.set(x+px,3.15,z+2.02);world.add(win)});for(const [tx,tz,h] of [[-2.75,-2.55,4], [2.75,-2.55,4],[-2.75,2.55,3.8],[2.75,2.55,3.8]]){const tower=new THREE.Mesh(new THREE.CylinderGeometry(.9,1.03,h,9),material(0xa89f91));tower.position.set(x+tx,h/2+.35,z+tz);world.add(tower);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.12,1.55,7),material(0x718ba0));roof.position.set(x+tx,h+1.12,z+tz);world.add(roof)}const flagPole=new THREE.Mesh(new THREE.CylinderGeometry(.05,.05,3,6),material(0x835a30));flagPole.position.set(x,7.2,z+.2);world.add(flagPole);const flag=new THREE.Mesh(new THREE.PlaneGeometry(1.65,.7),new THREE.MeshBasicMaterial({color:0xf0b933,side:THREE.DoubleSide}));flag.position.set(x+.82,8.2,z+.2);world.add(flag);const home=(hx:number,hz:number,roofColor:number)=>{const foundation=new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.35,.25,8),material(0x8a7050));foundation.position.set(hx,.48,hz);world.add(foundation);const walls=new THREE.Mesh(new THREE.CylinderGeometry(1.06,1.18,1.55,8),material(0xe0bd78));walls.position.set(hx,1.28,hz);world.add(walls);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.5,1.6,7),material(roofColor));roof.position.set(hx,2.85,hz);world.add(roof)};[[-13,5],[-15,8],[-14,-7],[-16,-10],[13,-5],[16,-3],[15,10],[7,14],[-5,-14]].forEach(([dx,dz],i)=>home(x+dx,z+dz,i%2?0x627492:0xc85b43));for(let band=0;band<4;band++)for(let i=0;i<42;i++){const a=i/42*Math.PI*2+band*.2,r=18+band*2.6,hx=x+Math.cos(a)*r,hz=z+Math.sin(a)*r*.76;if(hx>x+15&&Math.abs(hz-z)<4)continue;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.14,.22,1.15,6),material(0x704929));trunk.position.set(hx,.9,hz);world.add(trunk);const leaves=new THREE.Mesh(new THREE.ConeGeometry(.83,2.2,8),material(0x4f932f));leaves.position.set(hx,2.1,hz);world.add(leaves)}}
    addHomeRealm(-47,1)
    // Re-seat the green kingdom's woods beyond its meadow edge and keep the Ruby border crossing clear.
    const homeCenterX=-47,homeCenterZ=1
    world.children.slice().forEach(child=>{const mesh=child as THREE.Mesh,mat=mesh.material;if(mat instanceof THREE.MeshStandardMaterial&&(mat.color.getHex()===0x704929||mat.color.getHex()===0x4f932f)&&Math.hypot(mesh.position.x-homeCenterX,(mesh.position.z-homeCenterZ)/.76)<21)world.remove(mesh)})
    const addHomeEdgeTree=(tx:number,tz:number,scale=.9)=>{const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.14,.22,1.15,6),material(0x704929));trunk.position.set(tx,.9,tz);world.add(trunk);const leaves=new THREE.Mesh(new THREE.ConeGeometry(.83,2.2,8),material(0x4f932f));leaves.position.set(tx,2.1,tz);leaves.scale.setScalar(scale);world.add(leaves)}
    for(let band=0;band<4;band++)for(let i=0;i<44;i++){const a=i/44*Math.PI*2+band*.21,r=22+band*2.6,tx=homeCenterX+Math.cos(a)*r,tz=homeCenterZ+Math.sin(a)*r*.76;if(tx>homeCenterX+18&&Math.abs(tz-homeCenterZ)<4)continue;addHomeEdgeTree(tx,tz,.78+((i+band)%5)*.08)}
    // Home-realm landmark pass: the same recognizable village systems from the main kingdom.
    const homeX=-47,homeZ=1,homeRoadMat=material(0xd4d0bf)
    const cleanHomeMeadow=new THREE.Mesh(new THREE.CircleGeometry(20,42),material(0x91b989));cleanHomeMeadow.rotation.x=-Math.PI/2;cleanHomeMeadow.scale.z=.78;cleanHomeMeadow.position.set(homeX,.105,homeZ);world.add(cleanHomeMeadow)
    const cleanHomePlaza=new THREE.Mesh(new THREE.CircleGeometry(4.7,30),homeRoadMat);cleanHomePlaza.rotation.x=-Math.PI/2;cleanHomePlaza.position.set(homeX,.112,homeZ);world.add(cleanHomePlaza)
    const homeRoad=(x1:number,z1:number,x2:number,z2:number,width=1.1)=>{const dx=x2-x1,dz=z2-z1,distance=Math.hypot(dx,dz),bend=(.45+Math.abs(Math.sin(x1*7+z2*3))*.55)*Math.min(2.3,distance*.14),curve=new THREE.CatmullRomCurve3([new THREE.Vector3(x1,.11,z1),new THREE.Vector3(x1+dx*.3-dz/distance*bend,.11,z1+dz*.3+dx/distance*bend),new THREE.Vector3(x1+dx*.7+dz/distance*bend*.62,.11,z1+dz*.7-dx/distance*bend*.62),new THREE.Vector3(x2,.11,z2)]),left:THREE.Vector2[]=[],right:THREE.Vector2[]=[];for(let i=0;i<=24;i++){const p=curve.getPoint(i/24),t=curve.getTangent(i/24).normalize(),edge=width*.5*(.85+Math.sin(i*2.4)*.11);left.push(new THREE.Vector2(p.x-t.z*edge,-p.z-t.x*edge));right.push(new THREE.Vector2(p.x+t.z*edge,-p.z+t.x*edge))}const shape=new THREE.Shape();shape.moveTo(left[0].x,left[0].y);left.slice(1).forEach(p=>shape.lineTo(p.x,p.y));right.reverse().forEach(p=>shape.lineTo(p.x,p.y));shape.closePath();const road=new THREE.Mesh(new THREE.ShapeGeometry(shape),homeRoadMat);road.geometry.rotateX(-Math.PI/2);road.position.y=.12;world.add(road)}
    homeRoad(homeX,homeZ-4.5,homeX,homeZ-13,1.3);homeRoad(homeX+4.8,homeZ,homeX+13,homeZ,1.15);homeRoad(homeX-4.8,homeZ,homeX-13,homeZ+1,1.15);homeRoad(homeX,homeZ+4.6,homeX,homeZ+13,1.1);homeRoad(homeX+13,homeZ,homeX+10,homeZ-13,.85);homeRoad(homeX-13,homeZ,homeX-10,homeZ-8,.85)
    const homeWell=()=>{const g=new THREE.Group();g.position.set(homeX+2.25,.35,homeZ-12.15);world.add(g);const base=new THREE.Mesh(new THREE.CylinderGeometry(1.04,1.22,.38,10),material(0x9b988c));base.position.y=.19;g.add(base);const wall=new THREE.Mesh(new THREE.CylinderGeometry(.82,.98,.62,10),material(0xb9b4a8));wall.position.y=.58;g.add(wall);const water=new THREE.Mesh(new THREE.CircleGeometry(.69,12),material(0x86b6c5));water.rotation.x=-Math.PI/2;water.position.y=.92;g.add(water);[-.74,.74].forEach(px=>{const post=new THREE.Mesh(new THREE.BoxGeometry(.15,2.05,.15),material(0x825f42));post.position.set(px,1.64,0);g.add(post)});const roof=new THREE.Mesh(new THREE.ConeGeometry(1.27,.95,4),material(0x7a94a7));roof.position.y=2.75;roof.rotation.y=Math.PI/4;g.add(roof)}
    const homeWindmill=()=>{const g=new THREE.Group();g.position.set(homeX+10,.35,homeZ-13);world.add(g);const base=new THREE.Mesh(new THREE.CylinderGeometry(1.1,1.35,2.75,8),material(0xf1d58c));base.position.y=1.38;g.add(base);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.45,1.45,6),material(0x4d80b8));roof.position.y=3.5;g.add(roof);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.22,.22,.22,8),material(0x7a563d));hub.position.set(0,2.72,1.12);hub.rotation.x=Math.PI/2;g.add(hub);for(let i=0;i<4;i++){const blade=new THREE.Mesh(new THREE.BoxGeometry(.32,1.72,.08),material(i%2?0xf1ca50:0x4d80b8));blade.position.set(Math.sin(i*Math.PI/2)*.72,2.72+Math.cos(i*Math.PI/2)*.72,1.16);blade.rotation.z=-i*Math.PI/2;g.add(blade)}}
    const homeFarm=()=>{const fx=homeX+5,fz=homeZ-11,soil=new THREE.Mesh(new THREE.PlaneGeometry(5.1,3.6),material(0x887052));soil.rotation.x=-Math.PI/2;soil.position.set(fx,.13,fz);world.add(soil);for(let row=0;row<4;row++)for(let col=0;col<6;col++){const crop=new THREE.Mesh(new THREE.ConeGeometry(.1,.58,5),material((row+col)%4?0x7ea459:0xd2ba4d));crop.position.set(fx-1.65+col*.68,.4,fz-1.05+row*.72);world.add(crop)};[[0,-1.8,5.2,.13],[0,1.8,5.2,.13],[-2.6,0,.13,3.7],[2.6,0,.13,3.7]].forEach(([dx,dz,w,d])=>{const rail=new THREE.Mesh(new THREE.BoxGeometry(w,.14,d),material(0x86634a));rail.position.set(fx+dx,.48,fz+dz);world.add(rail)});const cottage=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.2,1.55,8),material(0xe0bd78));cottage.position.set(fx-3.4,1.13,fz+1.1);world.add(cottage);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.5,1.55,7),material(0xc85b43));roof.position.set(fx-3.4,2.68,fz+1.1);world.add(roof)}
    const homeStable=()=>{const g=new THREE.Group();g.position.set(homeX-6,.35,homeZ+7);world.add(g);const floor=new THREE.Mesh(new THREE.BoxGeometry(3.35,.18,2.65),material(0x9b7b58));floor.position.y=.09;g.add(floor);const back=new THREE.Mesh(new THREE.BoxGeometry(3.2,2.2,.18),material(0xb18d63));back.position.set(0,1.2,-1.2);g.add(back);[[-1.42,-1.08],[1.42,-1.08],[-1.42,1.08],[1.42,1.08]].forEach(([px,pz])=>{const post=new THREE.Mesh(new THREE.CylinderGeometry(.11,.14,2.65,6),material(0x72513a));post.position.set(px,1.33,pz);g.add(post)});const roof=new THREE.Mesh(new THREE.ConeGeometry(2.5,1.5,4),material(0x6f8fa0));roof.position.y=3.12;roof.rotation.y=Math.PI/4;g.add(roof);[-.65,.65].forEach(px=>{const horse=new THREE.Mesh(new THREE.SphereGeometry(.46,8,6),material(0x8a5d43));horse.scale.set(1.35,.78,.78);horse.position.set(px,.72,.1);g.add(horse)})}
    const homeMarket=()=>{const g=new THREE.Group();g.position.set(homeX+12,.35,homeZ+11);world.add(g);const table=new THREE.Mesh(new THREE.BoxGeometry(2.65,.7,1.15),material(0x8b674b));table.position.y=.65;g.add(table);const canopy=new THREE.Mesh(new THREE.ConeGeometry(2,.62,4),material(0x718fa3));canopy.position.y=2.52;canopy.rotation.y=Math.PI/4;g.add(canopy);[[-1.1,-.45],[1.1,-.45],[-1.1,.45],[1.1,.45]].forEach(([px,pz])=>{const pole=new THREE.Mesh(new THREE.CylinderGeometry(.06,.08,2.05,5),material(0x765139));pole.position.set(px,1.3,pz);g.add(pole)})}
    const homeLamp=(x:number,z:number)=>{const pole=new THREE.Mesh(new THREE.CylinderGeometry(.045,.06,1.35,6),material(0x5e4b3b));pole.position.set(x,.98,z);world.add(pole);const light=new THREE.Mesh(new THREE.OctahedronGeometry(.15),material(0xf2d77b,0xf2d77b));light.position.set(x,1.65,z);world.add(light)}
    const homeCampfire=()=>{const fire=new THREE.Group();fire.position.set(homeX-12.3,.34,homeZ-10.6);world.add(fire);const ash=new THREE.Mesh(new THREE.CylinderGeometry(.72,.86,.12,10),material(0x5b554c));ash.position.y=.08;fire.add(ash);for(let i=0;i<8;i++){const a=i*Math.PI*2/8,stone=new THREE.Mesh(new THREE.DodecahedronGeometry(.22,0),material(i%2?0x8d887d:0xa6a091));stone.position.set(Math.cos(a)*.82,.18,Math.sin(a)*.82);stone.scale.set(1,.58,.8);fire.add(stone)};[-.42,.42].forEach((offset,index)=>{const log=new THREE.Mesh(new THREE.CylinderGeometry(.12,.16,1.45,6),material(0x71442f));log.rotation.z=Math.PI/2;log.rotation.y=index?Math.PI/2:0;log.position.set(0,.25,offset);fire.add(log)});const ember=new THREE.Mesh(new THREE.SphereGeometry(.36,7,5),material(0xff983d,0xff983d));ember.scale.y=.32;ember.position.y=.34;fire.add(ember);const flame=new THREE.Mesh(new THREE.ConeGeometry(.4,.76,6),material(0xe85c2e));flame.position.y=.69;fire.add(flame);const inner=new THREE.Mesh(new THREE.ConeGeometry(.19,.48,6),material(0xffdc63));inner.position.set(.04,.72,.02);fire.add(inner)}
    const homeTrainingFence=()=>{const tx=homeX+8,tz=homeZ+6,ground=new THREE.Mesh(new THREE.CircleGeometry(2.05,12),material(0xbda978));ground.rotation.x=-Math.PI/2;ground.position.set(tx,.13,tz);world.add(ground);for(let i=0;i<7;i++){const a=i*Math.PI*2/7,post=new THREE.Mesh(new THREE.BoxGeometry(.15,.65,.15),material(0x7c583d));post.position.set(tx+Math.cos(a)*1.85,.45,tz+Math.sin(a)*1.85);world.add(post)};for(const [px,pz] of [[-.48,0],[.55,.35]]){const dummy=new THREE.Mesh(new THREE.CylinderGeometry(.07,.09,1.2,6),material(0x765139));dummy.position.set(tx+px,.75,tz+pz);world.add(dummy);const target=new THREE.Mesh(new THREE.SphereGeometry(.28,7,6),material(0xd7ba73));target.position.set(tx+px,1.42,tz+pz);world.add(target)}}
    homeWell();homeWindmill();homeFarm();homeStable();homeMarket();homeCampfire();homeTrainingFence();[[-2,6], [2,6],[-12,5],[-12,-8],[12,-5],[7,12]].forEach(([dx,dz])=>homeLamp(homeX+dx,homeZ+dz))
    const rubySheep:{group:THREE.Group;cx:number;cz:number;phase:number}[]=[]
    const addSheep=(x:number,z:number,phase:number)=>{const sheep=new THREE.Group();world.add(sheep);const body=new THREE.Mesh(new THREE.SphereGeometry(.43,9,7),material(0xf4d7d2));body.scale.set(1.3,.82,.82);body.position.y=.55;sheep.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.19,7,5),material(0x703745));head.position.set(.48,.62,0);sheep.add(head);for(const [lx,lz] of [[-.24,-.22],[-.24,.22],[.24,-.22],[.24,.22]]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.035,.045,.38,5),material(0x4a2831));leg.position.set(lx,.2,lz);sheep.add(leg)};rubySheep.push({group:sheep,cx:x,cz:z,phase})}
    addSheep(-15,-10,0);addSheep(-15,-10,2.1);addSheep(13,8,1.1);addSheep(13,8,3.3)
    const addRubyTree=(x:number,z:number,scale=.9)=>{const tree=new THREE.Group();tree.position.set(x,.3,z);tree.scale.setScalar(scale);world.add(tree);const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.13,.22,1.35,6),material(0x401f31));trunk.position.y=.68;tree.add(trunk);for(let i=0;i<3;i++){const crown=new THREE.Mesh(new THREE.OctahedronGeometry(.68-i*.08,0),material(i===1?0xa52e4d:0x772844));crown.position.set((i-1)*.27,1.65+i*.32,(i%2-.5)*.2);crown.scale.y=1.55;crown.castShadow=true;tree.add(crown)}}
    // Dense thorn-crystal woods extend well past the camera frame, with one deliberate palace exit opening.
    for(let band=0;band<8;band++)for(let i=0;i<58;i++){const angle=i/58*Math.PI*2+band*.18,radius=25+band*3+Math.sin(i*3.1+band)*.8,x=Math.cos(angle)*radius*1.18,z=Math.sin(angle)*radius*.82;if((z>9&&Math.abs(x)<5.5)||(x < -18&&Math.abs(z)<7))continue;addRubyTree(x,z,.72+((i+band*2)%7)*.09)}
    for(let i=0;i<95;i++){const angle=i*2.16,r=7+(i%9)*1.55;const shard=new THREE.Mesh(new THREE.ConeGeometry(.035+(i%3)*.018,.22+(i%4)*.08,4),material(i%5?0xa83e50:0xff5b6f));shard.position.set(Math.cos(angle)*r,.14,Math.sin(angle)*r*.74);shard.rotation.z=(i%4-1.5)*.25;world.add(shard)}
    for(let i=0;i<45;i++){const a=i*2.4,r=17+(i%5)*2.4;const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.25+(i%4)*.09,0),material(i%4?0x6c2e3d:0xd84b59));rock.position.set(Math.cos(a)*r,.2,Math.sin(a)*r*.72);rock.rotation.y=i;world.add(rock)}
    const resize=()=>{const {width,height}=host.getBoundingClientRect(),half=13.5,aspect=width/height;camera.left=-half*aspect;camera.right=half*aspect;camera.top=half;camera.bottom=-half;renderer.setSize(width,height,false);camera.updateProjectionMatrix()};resize();window.addEventListener('resize',resize)
    const yaw=Math.atan2(27,24),height=29
    let panX=0,panZ=0,targetPanX=0,targetPanZ=0,zoom=1,targetZoom=1,dragging=false,lastX=0,lastY=0,frame=0
    const down=(event:PointerEvent)=>{dragging=true;lastX=event.clientX;lastY=event.clientY;host.setPointerCapture(event.pointerId)}
    const move=(event:PointerEvent)=>{if(!dragging)return;const dx=event.clientX-lastX,dy=event.clientY-lastY,pan=.055/zoom;targetPanX=Math.max(-53,Math.min(31,targetPanX-dx*Math.cos(yaw)*pan-dy*Math.sin(yaw)*pan));targetPanZ=Math.max(-25,Math.min(25,targetPanZ+dx*Math.sin(yaw)*pan-dy*Math.cos(yaw)*pan));lastX=event.clientX;lastY=event.clientY}
    const up=(event:PointerEvent)=>{dragging=false;if(host.hasPointerCapture(event.pointerId))host.releasePointerCapture(event.pointerId)}
    const wheel=(event:WheelEvent)=>{event.preventDefault();targetZoom=Math.max(.72,Math.min(1.55,targetZoom-event.deltaY*.0012))}
    host.addEventListener('pointerdown',down);host.addEventListener('pointermove',move);host.addEventListener('pointerup',up);host.addEventListener('pointercancel',up);host.addEventListener('wheel',wheel,{passive:false})
    const animate=()=>{frame=requestAnimationFrame(animate);const time=performance.now()*.001;panX+=(targetPanX-panX)*.14;panZ+=(targetPanZ-panZ)*.14;zoom+=(targetZoom-zoom)*.13;camera.zoom=zoom;camera.updateProjectionMatrix();camera.position.set(Math.cos(yaw)*35+panX,height,Math.sin(yaw)*35+panZ);camera.lookAt(panX,.8,panZ);world.rotation.y=Math.sin(time*.16)*.007;rubySheep.forEach(sheep=>{const a=time*.42+sheep.phase;sheep.group.position.set(sheep.cx+Math.cos(a)*1.12,.03,sheep.cz+Math.sin(a)*.72);sheep.group.rotation.y=Math.atan2(-Math.cos(a),-Math.sin(a))});renderer.render(scene,camera)};animate()
    return()=>{cancelAnimationFrame(frame);window.removeEventListener('resize',resize);host.removeEventListener('pointerdown',down);host.removeEventListener('pointermove',move);host.removeEventListener('pointerup',up);host.removeEventListener('pointercancel',up);host.removeEventListener('wheel',wheel);renderer.dispose();host.removeChild(renderer.domElement)}
  },[])
  return <section className="ruby-battle-map" aria-label="Empress Ruby battle map"><div ref={mountRef} className="ruby-battle-canvas" /><header><span>EMPERESS RUBY'S DOMAIN</span><b>CRIMSON JEWEL KINGDOM</b></header><button className="ruby-retreat" onClick={onBack}>‹ <span>RETREAT</span></button><aside className={`ruby-chat${chatOpen ? '' : ' closed'}`}><button className="ruby-chat-title" onClick={() => setChatOpen(!chatOpen)}>FIELD CHAT <span>{chatOpen ? '−' : '+'}</span></button>{chatOpen && <><div className="ruby-chat-log"><p><b>SCOUT:</b> Ruby palace is ahead.</p><p><b>YOU:</b> Keep the line moving.</p></div><div className="ruby-chat-quick"><button>Rally here</button><button>Need support</button></div></>}</aside><aside className="ruby-commands"><p>BATTLE COMMANDS</p><b>YOUR KINGDOM</b><small>3 squads ready · 2 actions</small><div><button>⚔<em>MARCH</em></button><button>◈<em>SCOUT</em></button><button>♜<em>FORTIFY</em></button><button>✦<em>RALLY</em></button></div><button className="ruby-end-turn">END TURN ›</button></aside><div className="ruby-pan-tip">DRAG THE MAP TO PAN · SCROLL TO ZOOM</div></section>
}
