import { useEffect, useRef } from 'react'
import * as THREE from 'three'

type TroopKind='shield'|'spear'|'mage'|'archer'
const troops:{kind:TroopKind;name:string;role:string}[]=[{kind:'shield',name:'SHIELD TOAD',role:'FRONTLINE DEFENDER'},{kind:'spear',name:'SPEAR SCOUT',role:'FAST MELEE'},{kind:'mage',name:'MUSHROOM MAGE',role:'ARCANE SUPPORT'},{kind:'archer',name:'BERRY ARCHER',role:'RANGED STRIKER'}]
const mat=(color:number)=>new THREE.MeshStandardMaterial({color,roughness:.8,flatShading:true})

const TroopPreview=({kind}:{kind:TroopKind})=>{
  const ref=useRef<HTMLDivElement>(null)
  useEffect(()=>{const host=ref.current;if(!host)return;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,30),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(170,150);host.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x675158,2));const light=new THREE.DirectionalLight(0xffe7b3,2);light.position.set(-3,5,4);scene.add(light);const g=new THREE.Group();scene.add(g);const colors={shield:0x4d80b8,spear:0xd85c43,mage:0x8b5cb6,archer:0x5f9b63}[kind],body=new THREE.Mesh(new THREE.CylinderGeometry(.38,.45,.88,7),mat(colors));body.position.y=.75;g.add(body);const head=new THREE.Mesh(new THREE.DodecahedronGeometry(.37),mat(0xf0c58e));head.position.y=1.42;g.add(head);const legs:THREE.Mesh[]=[];[[-.16,-.1],[.16,.1]].forEach(([x,z])=>{const leg=new THREE.Mesh(new THREE.CylinderGeometry(.065,.075,.58,5),mat(0x493842));leg.position.set(x,.28,z);g.add(leg);legs.push(leg)});if(kind==='shield'){const shield=new THREE.Mesh(new THREE.CylinderGeometry(.46,.46,.12,8),mat(0xe4c45f));shield.rotation.x=Math.PI/2;shield.position.set(.42,.8,.1);g.add(shield);const helm=new THREE.Mesh(new THREE.ConeGeometry(.47,.42,7),mat(0x6c8aa4));helm.position.y=1.8;g.add(helm)}if(kind==='spear'){const spear=new THREE.Mesh(new THREE.CylinderGeometry(.04,.04,2.05,6),mat(0x765139));spear.position.set(.45,1.25,0);spear.rotation.z=-.14;g.add(spear);const tip=new THREE.Mesh(new THREE.ConeGeometry(.13,.4,5),mat(0xd9e8eb));tip.position.set(.59,2.27,0);tip.rotation.z=-.14;g.add(tip)}if(kind==='mage'){const hat=new THREE.Mesh(new THREE.ConeGeometry(.58,.92,7),mat(0x6a4693));hat.position.y=1.98;hat.rotation.z=-.12;g.add(hat);const orb=new THREE.Mesh(new THREE.OctahedronGeometry(.17),mat(0x8ce7ed));orb.position.set(.48,1.6,0);g.add(orb)}if(kind==='archer'){const hood=new THREE.Mesh(new THREE.ConeGeometry(.5,.58,7),mat(0x4d804e));hood.position.y=1.76;g.add(hood);const bow=new THREE.Mesh(new THREE.TorusGeometry(.38,.03,5,12,Math.PI),mat(0x80583c));bow.position.set(.43,1.02,.04);bow.rotation.y=Math.PI/2;g.add(bow)}camera.position.set(3,2.7,5);camera.lookAt(0,1,0);let frame=0;const animate=()=>{frame=requestAnimationFrame(animate);const t=performance.now()*.001;g.rotation.y=Math.sin(t*.8)*.38;g.position.y=Math.sin(t*2)*.04;legs.forEach((leg,i)=>leg.rotation.z=Math.sin(t*8+(i%2)*Math.PI)*.5);renderer.render(scene,camera)};animate();return()=>{cancelAnimationFrame(frame);renderer.dispose();host.removeChild(renderer.domElement)}},[kind])
  return <div ref={ref} className="troop-preview" />
}

export const TroopRoster=({onClose}:{onClose:()=>void})=><section className="troop-roster" aria-label="Troop roster"><div className="troop-roster-panel"><button className="troop-roster-close" onClick={onClose}>×</button><header><small>YOUR KINGDOM</small><h2>TROOP ROSTER</h2><p>MEET YOUR FIRST FOUR UNITS</p></header><div className="troop-roster-grid">{troops.map(troop=><article key={troop.kind}><TroopPreview kind={troop.kind}/><b>{troop.name}</b><small>{troop.role}</small></article>)}</div></div></section>
